# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: 131220237071.dkr.ecr.us-east-2.amazonaws.com/betaapp
  tag: latest
  config: [app-config]
  secret: [betaapp-mongo-secret]
  pullPolicy:  Always 
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
  # readinessProbe: {}
  # Example (replace readinessProbe: {} with the following):
  # readinessProbe:
  #   httpGet:
  #     path: /readiness
  #     port: 8081
  #   initialDelaySeconds: 3
  #   periodSeconds: 5
  # livenessProbe: {}
  # Example (replace livenessProbe: {} with the following)::
  livenessProbe:
    httpGet:
      path: /liveness
      port: 8081
    initialDelaySeconds: 40
    periodSeconds: 10  
domain: evalsocket.in
certificate: betaapp-letsencrypt-dev
ingress:
  enabled: false 
service:
  name: Node
  type: LoadBalancer
  servicePort: 80
  targetPort: 8081
  nodePort: 30163
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70