apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: betaapp-
namespace: master
commonLabels:
  environment: prod
  owner: yuvraj
commonAnnotations:
  oncallPager: 800-555-1215
  team : devops
generatorOptions:
  labels: {}
  annotations: {}
  disableNameSuffixHash: true
resources:
- ../base
configMapGenerator:
- name: app-config
  literals:
  - PORT=8081

