apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./letsencrypt.yaml
namePrefix: betaapp-
namespace: dev
commonLabels:
  environment: dev
  owner: yuvraj
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: mongo-secret
  literals:
  - MONGODB_URI="mongodb://INPUTUSERNAME:INPUTPASSWORD@release-name-mongodb.database.svc.cluster.local:27017/betaapp"

